### ISSUE TITLE
Criar Wireframe da tela Adicionar aos Favoritos

### ISSUE THREAD

**Issue by gxudre** [igoraoliveira/PiMobile#136]

**Comment by igoraoliveira** [comment]
Um dos botões é para adicionar aos favoritos.

![Image](https://github.com/igoraoliveira/PiMobile/assets/88742045/4b88ea58-12fe-4b87-8389-903bbdcbed4f)

**Comment by igoraoliveira** [comment]
Um dos botões é para adicionar aos favoritos.
