### ISSUE TITLE
Design Tela de busca, Tela de busca vazia e Tela de cadastro de Filme

### ISSUE THREAD

**Issue by gxudre** [igoraoliveira/PiMobile#138]

**Comment by jose-santos88** [comment]
![Image](https://github.com/igoraoliveira/PiMobile/assets/128557410/23964729-811a-450a-9e1a-933479169be0)
![Image](https://github.com/igoraoliveira/PiMobile/assets/128557410/4aabe6f5-0d4c-4684-9ab1-50a58d86ddb8)
![Image](https://github.com/igoraoliveira/PiMobile/assets/128557410/d69e4191-4a6b-4e3c-b74d-8caea71b6340)
