### ISSUE TITLE
Design tela de Cadastro e Tela de login

### ISSUE THREAD

**Issue by gxudre** [igoraoliveira/PiMobile#140]

**Comment by igoraoliveira** [comment]
![Image](https://github.com/igoraoliveira/PiMobile/assets/88742045/7f5d41d0-2352-4994-831c-e7faa8d7c776)
![Image](https://github.com/igoraoliveira/PiMobile/assets/88742045/446de7c5-c599-4621-911f-0079a0ec0d76)
