### ISSUE TITLE
Design Tela de Favoritos, Tela de Favoritos Vazia e Navegação entre Telas

### ISSUE THREAD

**Issue by gxudre** [igoraoliveira/PiMobile#141]

**Comment by Arthurmartoneto** [comment]
![desing](https://github.com/igoraoliveira/PiMobile/assets/104384080/586a68dd-fe5d-4143-aca1-5b809ae15465)
![navigation](https://github.com/igoraoliveira/PiMobile/assets/104384080/4c99485d-15ea-499b-9670-59b727ad58a1)
